packages:
  - playground
  - docs
  - packages/*
  - examples/*

ignoreWorkspaceRootCheck: true
shellEmulator: true

catalogs:
  build:
    oxc-parser: ^0.93.0
    oxc-walker: ^0.5.2
    recast: ^0.23.11
  cli:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.1.0
    bumpp: ^10.2.3
    eslint: ^9.36.0
    lint-staged: ^16.2.3
    simple-git-hooks: ^2.13.1
    tsdown: ^0.15.6
    tsx: ^4.20.6
    typescript: ^5.9.3
  docs:
    '@iconify-json/logos': ^1.2.9
    unocss: ^66.5.2
    vitepress: ^1.6.4
  testing:
    tinyexec: ^1.0.1
    vitest: ^3.2.4
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^24.6.2
  vite:
    '@vitejs/plugin-vue': ^6.0.1
    vite: npm:rolldown-vite@latest
    # vite: ^7.1.8
    vite-plugin-inspect: ^11.3.3
  vue:
    vue: ^3.5.22

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
